[workspace]
resolver = "3"
members = [
  "crates/config",
  "crates/cursor",
  "crates/formats",
  "crates/precursor",
]

[workspace.package]
version = "0.1.0"
edition = "2024"
license = "GPL-3.0-or-later"

[workspace.dependencies]
crate_config.path = "crates/config"
crate_cursor.path = "crates/cursor"
crate_formats.path = "crates/formats"

byteorder = "1.5.0"
num_enum = "0.7.6"
toml = "1.1.4"

[workspace.dependencies.clap]
version = "4.6.5"
features = ["derive"]

[workspace.dependencies.serde]
version = "1.0.229"
features = ["derive"]
