[package]
name = "precursor"
version.workspace = true
edition.workspace = true
description = "Precursor is a tool for building cross-platform cursor themes."
license.workspace = true

[dependencies]
clap.workspace = true
crate_config.workspace = true
crate_cursors.workspace = true
crate_images.workspace = true
toml.workspace = true
